airflow:
  extraPipPackages:
    - "pandas"
    - "sqlalchemy"
    - "psycopg2-binary"
    - "scipy"
    - "requests"
    - "python-dotenv"
    - "fbprophet"
    - "scikit-learn"
    - "keras"
    - "tensorflow"

workers:
  resources:
    requests:
      cpu: "1000m"
      memory: "1Gi"

  replicas: 1

  autoscaling:
    enabled: true
    maxReplicas: 2
    metrics: []

dags:
  git:
    url: "https://airflow:airflow@github.com/org/airflow_dags.git"
    ref: dev-branch
    gitSync:
      enabled: true
      username: "airflow"
      password: "airflow"
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
      image:
        repository: alpine/git
        tag: latest
        pullPolicy: IfNotPresent
      refrestTime: 60